---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: Optional Tasks
  hosts: webservers, nfs, db
  user: ec2-user
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: create a sample directory
      file:
        path: /home/sample
        state: directory

    - name: Install Git
      yum:
        name: git
        state: latest

    - name: create a file
      file:
        path: /home/sample/sample.txt
        state: directory

    - name: set timezone
      timezone:
        name: Africa/Lagos
