pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages{
        stage("Workspace Cleanup") {
            steps {
            dir("${WORKSPACE}") {
                deleteDir()
            }
            }
        }

        stage('Checkout SCM') {
            steps{
            git branch: 'main', credentialsId: '63657397-4801-4694-bd3a-1b5df76a76d1', url: 'https://github.com/Kingkellee/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
        steps {
            sh 'echo ${WORKSPACE}' 
            sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
        }
        }

        stage('Run Ansible playbook') {
        steps {
            ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
            }
        }

        stage('Clean Workspace after build'){
        steps{
            cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
        }
        }
    }

}