---
# - hosts: all
# - name: Include dynamic variables
#   import_playbook: ../static-assignments/common.yml
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - hosts: webservers
# - name: Webserver assignment
#   import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: db
# - name: database mysql configuration
#   import_playbook: ../static-assignments/mysql-database.yml

# - hosts: nginx
# - name: Loadbalancers assignment
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required

- hosts: artifactory
- name: artifactory assignment
  ansible.builtin.import_playbook: ../static-assignments/artifactory.yml
